"""Auto migration

Revision ID: 1e4fbe2ccbd9
Revises: 7aa4e0434a89
Create Date: 2024-08-24 09:47:15.383795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e4fbe2ccbd9'
down_revision = '7aa4e0434a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=70),
               existing_nullable=False)
        batch_op.drop_constraint('users_phone_number_key', type_='unique')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('confirmation_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_phone_number_key', ['phone_number'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
